# Generated by Django 4.2.2 on 2024-02-23 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField()),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='image')),
                ('top1_text', models.CharField(max_length=150)),
                ('top1_image', models.ImageField(upload_to='image')),
                ('top1_description', models.TextField(max_length=500)),
                ('top2_text', models.CharField(max_length=150)),
                ('top2_image', models.ImageField(upload_to='image')),
                ('top2_description', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post_filter', models.CharField(choices=[('F', 'Feature'), ('T', 'Trending'), ('PR', 'Promotion')], default='F', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
    ]
